reparacion:
    resource: "@ReparacionBundle/Controller/"
    type:     annotation
    prefix:   /reparacion/

solicitud:
    resource: "@SolicitudBundle/Controller/"
    type:     annotation
    prefix:   /solicitud/

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
