# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        EG\IdiomaBundle\Entity\Usuario:
            algorithm:           md5
            encode_as_base64:    false
            iterations:          1

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        usuEmpAdm:
            entity: { class: EG\IdiomaBundle\Entity\Usuario, property: login }

    firewalls:
          # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        EmpAdm:
             pattern: ^/
             anonymous: ~
             provider: usuEmpAdm
             form_login:
                 login_path: login
                 check_path: login_check
                 default_target_path: /
                 always_use_default_target_path: true
             access_denied_url: /login
             logout:
                 path: logout
                 target: login
            # activate different ways to authenticate
            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
          - { path: ^/login,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }
          #- { path: ^/*,      roles: IS_AUTHENTICATED_FULLY }
