<?php

namespace ReparacionBundle\Repository;

/**
 * AsignacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionRepository extends \Doctrine\ORM\EntityRepository
{

	public function findReportePorFechas($inicio,$fin){
        $em = $this->getEntityManager();

        $resultado=$em->createQuery("SELECT asi.id as tecId, concat(asi.paterno,' ',asi.materno,' ',asi.nombre) as tecnico, count(a.id) as cantidad FROM ReparacionBundle:Asignacion a
        	inner join a.asignado asi
                                    where a.fechaPlazo>=:inicio and a.fechaPlazo<=:fin
                                    group by asi.id
                                    ")
                                    ->setParameter('inicio',$inicio)
                                    ->setParameter('fin',$fin)
                                    ->getResult();

        return $resultado;
    }
}
