<?php

namespace ReparacionBundle\Repository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends \Doctrine\ORM\EntityRepository
{

	public function findAjaxValue($term){
        $em = $this->getEntityManager();
        $term = str_replace(' ', '%', $term);
        $consul = $em->createQuery('SELECT z FROM ReparacionBundle:Cliente z
                                        WHERE  z.paterno LIKE \'%'.$term.'%\'
                                        OR  z.nombre LIKE \'%'.$term.'%\'');
        $resp = $consul->getResult();
        return $resp;
    }
}
