<?php

namespace ReparacionBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * DetalleSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleSolicitudRepository extends \Doctrine\ORM\EntityRepository
{
	public function listadoAjax($cantidad,$comienza,$campo,$dir,$buscar)
    {
        $em = $this->getEntityManager();
        $consul = $em->createQuery('SELECT ds FROM ReparacionBundle:DetalleSolicitud ds left join ds.asignacion a  inner join ds.solicitud s
        where a.id is null
        AND ds.descripcion LIKE :value
        ORDER BY '.$campo.' '.$dir)
            ->setParameter('value',$buscar.'%')
            ->setFirstResult($comienza)
            ->setMaxResults($cantidad);

        $paginator = new Paginator($consul, $fetchJoinCollection = true);
        $c = count($paginator);
        $resp = $consul->getResult();
        return array('result'=>$resp,'cant'=>$c);
    }
}
