<?php

namespace ReparacionBundle\Repository;

/**
 * DetalleRepuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleRepuestoRepository extends \Doctrine\ORM\EntityRepository
{
}
