<?php

namespace ReparacionBundle\Repository;

/**
 * JefeTecnicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JefeTecnicoRepository extends \Doctrine\ORM\EntityRepository
{
}
