<?php

namespace ReparacionBundle\Repository;

/**
 * RecepcionistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecepcionistaRepository extends \Doctrine\ORM\EntityRepository
{
}
