<?php

namespace ReparacionBundle\Repository;

/**
 * RepuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepuestoRepository extends \Doctrine\ORM\EntityRepository
{
}
