<?php

namespace TotaisBundle\Repository;

/**
 * JugadorEquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JugadorEquipoRepository extends \Doctrine\ORM\EntityRepository
{
}
