<?php

namespace SolicitudBundle\Repository;

/**
 * DetalleEmpleadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleEmpleadoRepository extends \Doctrine\ORM\EntityRepository
{
}
