<?php

namespace SolicitudBundle\Repository;

/**
 * MedicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicoRepository extends \Doctrine\ORM\EntityRepository
{
}
