<?php

namespace SolicitudBundle\Repository;

/**
 * MedicoCentroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicoCentroRepository extends \Doctrine\ORM\EntityRepository
{
}
