<?php

namespace SolicitudBundle\Repository;

/**
 * PacienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PacienteRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAjaxValue($term){
        $em = $this->getEntityManager();
        $term = str_replace(' ', '%', $term);
        $consul = $em->createQuery('SELECT z FROM SolicitudBundle:Paciente z
                                        WHERE  z.paterno LIKE \'%'.$term.'%\' OR  z.nombre LIKE \'%'.$term.'%\'');
        $resp = $consul->getResult();
        return $resp;
    }
}
