<?php

namespace SolicitudBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * SolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudRepository extends \Doctrine\ORM\EntityRepository
{
	public function listadoAjax($cantidad,$comienza,$campo,$dir,$buscar)
    {
        $em = $this->getEntityManager();
        $consul = $em->createQuery('SELECT s FROM SolicitudBundle:Solicitud s inner join s.paciente p
        WHERE p.paterno LIKE :value
        ORDER BY '.$campo.' '.$dir)
            ->setParameter('value',$buscar.'%')
            ->setFirstResult($comienza)
            ->setMaxResults($cantidad);

        $paginator = new Paginator($consul, $fetchJoinCollection = true);
        $c = count($paginator);
        $resp = $consul->getResult();
        return array('result'=>$resp,'cant'=>$c);
    }

    public function findReportePorFechas($inicio,$fin){
        $em = $this->getEntityManager();

        $resultado=$em->createQuery('SELECT s FROM SolicitudBundle:Solicitud s
                                    where s.fechaEnvio>=:inicio and s.fechaEnvio<=:fin
                                    ORDER BY s.fechaEnvio ASC')
                                    ->setParameter('inicio',$inicio)
                                    ->setParameter('fin',$fin)
                                    ->getResult();

        return $resultado;
    }
}
